version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: premarket-postgres
    environment:
      POSTGRES_DB: trading_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      TZ: America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  premarket-scanner:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: premarket-scanner
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: trading_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      TZ: America/New_York
      PYTHONPATH: /app
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: